### ISSUE TITLE
First one

### ISSUE THREAD

**Issue by ghost** [ChrysanthCow/unwieldy#2]
boznia and heregovina has no beaches @MerchantPug
![dnnsgofa5ui81](https://user-images.githubusercontent.com/65086725/159489989-9f8aea33-9f2c-486f-84ee-346a7191cd5d.png)

**Comment by ghost** [comment]
tw: the creator has made an other first one, frick them

**Comment by MerchantPug** [comment]
I agree
https://user-images.githubusercontent.com/81167232/159490302-ab54b468-921a-4d87-9547-7fa460c66f22.mp4

**Comment by ChrysanthCow** [comment]
**L**

https://user-images.githubusercontent.com/81167232/159490409-9dcc4cea-b26b-4c4c-b3d8-63f5117911c0.mp4
